sudo: required

language: python

services:
  - docker
  
install:
  - docker pull python:3.5

script:
  - travis_wait 45 docker build --tag fakanal/nltk:0.2 ./naturalLanguageProcessing
  - docker login -u fakanal -p fakanal
  - docker push fakanal/nltk:0.2
